This is homework assignment #1. Please use this file to write code and submit separate file with answers provided.

1 Set $X = \sqrt{17}$ rounded to the nearest digit. Print the message using the variable "Approximate square root of 17 is X". Where X is the variable.

In [1]:
import numpy as np
import pandas as pd
X = round(np.sqrt(17))
print("Approximate square root of 17 is", X)

Approximate square root of 17 is 4.0


2 Covert all words to lowcase and drop all numbers and punctiation from the string.
S = "(1) An official wants to multiply subordinates, not rivals and (2) Officials make work for each other. [Parkinson] notes in particular that the total of those employed inside a bureaucracy rose by 5-7% per year irrespective of any variation in the amount of work (if any) to be done.”

In [79]:
import string
dir(string)
S = "(1) An official wants to multiply subordinates, not rivals and (2) Officials make work for each other. [Parkinson] notes in particular that the total of those employed inside a bureaucracy rose by 5-7% per year irrespective of any variation in the amount of work (if any) to be done."
lower = S.lower()
#letters_only = filter(S.isalpha(), S)
words_only = ''.join(i for i in lower if i.isalpha() or i.isspace() )
print(words_only)



 an official wants to multiply subordinates not rivals and  officials make work for each other parkinson notes in particular that the total of those employed inside a bureaucracy rose by  per year irrespective of any variation in the amount of work if any to be done


In [102]:
#another way to do it...but it doesn't print out in a useful format
for i in lower:
    if i.replace(' ','').isalpha():
        print(i)
    else:
        print("")
    






a
n

o
f
f
i
c
i
a
l

w
a
n
t
s

t
o

m
u
l
t
i
p
l
y

s
u
b
o
r
d
i
n
a
t
e
s


n
o
t

r
i
v
a
l
s

a
n
d





o
f
f
i
c
i
a
l
s

m
a
k
e

w
o
r
k

f
o
r

e
a
c
h

o
t
h
e
r



p
a
r
k
i
n
s
o
n


n
o
t
e
s

i
n

p
a
r
t
i
c
u
l
a
r

t
h
a
t

t
h
e

t
o
t
a
l

o
f

t
h
o
s
e

e
m
p
l
o
y
e
d

i
n
s
i
d
e

a

b
u
r
e
a
u
c
r
a
c
y

r
o
s
e

b
y






p
e
r

y
e
a
r

i
r
r
e
s
p
e
c
t
i
v
e

o
f

a
n
y

v
a
r
i
a
t
i
o
n

i
n

t
h
e

a
m
o
u
n
t

o
f

w
o
r
k


i
f

a
n
y


t
o

b
e

d
o
n
e



3 Create a list of vegetables : carrot, potato, tomato, cabbage. Extract the first and last vegetable into another list. 

In [35]:
L = ['carrot', 'potato', 'tomato', 'cabbage']
F = [L[0],L[3]]
print(F)

['carrot', 'cabbage']


4  Create a vector from 0 to 9, extract elements on positions 2-4, and  on positions 7-9 into a another vector     

In [36]:
num = [0,1,2,3,4,5,6,7,8,9]
first = num[2:5]
second = num[7:10]
answer= first + second
print(answer)

[2, 3, 4, 7, 8, 9]


5 Create a vector of squared number from 3 to 13 using a loop, extract the smallest, the largest number and the lenght of the vector.

In [37]:
nums = []
for i in range(3, 14):
    nums.append(i*i)
print("Min", min(nums),"Max", max(nums), "Length", len(nums))



Min 9 Max 169 Length 11


6 Create a vector from  2 to 13, and a vector from 56 to 59. Then insert the second list in the position 5 of the first.

In [38]:
one= np.arange(2,14)
o=one.tolist()

two = np.arange(56,60)
t=two.tolist()

three = o[0:4]+ t + o[5:]

print(three)


[2, 3, 4, 5, 56, 57, 58, 59, 7, 8, 9, 10, 11, 12, 13]


7 Loop over the number from 17 to 36. Set up a condition under which you print the current looping number and print if it is even or odd.

In [39]:
for i in range(17,37):    
    if i % 2 == 0: print(i, "Even")
    else: print(i, "Odd")

17 Odd
18 Even
19 Odd
20 Even
21 Odd
22 Even
23 Odd
24 Even
25 Odd
26 Even
27 Odd
28 Even
29 Odd
30 Even
31 Odd
32 Even
33 Odd
34 Even
35 Odd
36 Even


8 Create a function that transforms an argument. First is takes a square root of the argument, then it adds 5, finally divides it by 7. Run the example with argument x = 5

In [40]:
def function(x):
    a=(np.sqrt(x)+5)/7
    return(a)

function(5)

1.0337239967856842

9 Create a 3x3 matrix with elements from 1 to 9 and add a row to the bottom of the matrix with number 11 13 15. 

In [46]:
matrix= np.arange(1,10).reshape(3,3)
matrix= np.asmatrix(matrix)
y = [11,13,15]
new_matrix=np.vstack([matrix, y])
print(matrix,"Matrix")
print( new_matrix,"Bigger Matrix")

[[1 2 3]
 [4 5 6]
 [7 8 9]] Matrix
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 13 15]] Bigger Matrix
